# Generated by Django 6.0.5 on 2026-05-10 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_hp', models.PositiveIntegerField(default=0)),
                ('used_hit_dice', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('xp', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdom', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charisma', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('has_shield', models.BooleanField(default=False)),
                ('pp', models.PositiveIntegerField(default=0)),
                ('gp', models.PositiveIntegerField(default=0)),
                ('sp', models.PositiveIntegerField(default=0)),
                ('cp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='reference_data.alignment')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='reference_data.armor')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='reference_data.background')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='reference_data.characterclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='reference_data.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='reference_data.weapon')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.skill')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='characters', through='characters.CharacterSkill', to='reference_data.skill'),
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.spell')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='characters', through='characters.CharacterSpell', to='reference_data.spell'),
        ),
        migrations.AddConstraint(
            model_name='characterskill',
            constraint=models.UniqueConstraint(fields=('character', 'skill'), name='unique_character_skill'),
        ),
        migrations.AddConstraint(
            model_name='characterspell',
            constraint=models.UniqueConstraint(fields=('character', 'spell'), name='unique_character_spell'),
        ),
    ]
